version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  connect:
    image: confluentinc/cp-kafka-connect:5.3.0
    environment: 
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_ADVERTISED_HOST_NAME=kafka
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID=local-connect-test
      - CONNECT_CONFIG_STORAGE_TOPIC=local-connect-test-config
      - CONNECT_OFFSET_STORAGE_TOPIC=local-connect-test-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=local-connect-test-status
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=localhost
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=localhost
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_LOG4J_ROOT_LOGLEVEL=INFO
      - CONNECT_PLUGIN_PATH=/usr/share/java,/etc/kafka-connect/jars
    ports:
      - 8083:8083
  manager:
    image: zenko/kafka-manager:1.3.3.22
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - 9000:9000
  connect-ui:
    image: landoop/kafka-connect-ui:0.9.7
    ports:
      - 8000:8000
    environment:
      - CONNECT_URL=connect:8083
